import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import Header from "./components/Header";
import Script from 'next/script';

const lineseed = localFont({
  src: [
    {
      path: './fonts/LineSeed/lineseedsansth_rg-webfont.woff2',
      weight: "400",
    },
    {
      path: './fonts/LineSeed/lineseedsansth_bd-webfont.woff2',
      weight: "700",
    },
    {
      path: './fonts/LineSeed/lineseedsansth_th-webfont.woff2',
      weight: "300",
    }
  ]
}
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-screen bg-slate-100 antialiased ${lineseed.className}`}>
        <Header />
        {children}
        <Script id='nav' src='/js/nav.js' />
        </body>
    </html>
  );
}
